Send error messages to stdout.

diff --git a/bin/lcinit b/bin/lcinit
--- a/bin/lcinit
+++ b/bin/lcinit
@@ -1,12 +1,12 @@
 #! /usr/bin/env bash
 
 if [[ $# -ne 1 ]]; then
-  echo "error: usage lcinit <problem number>"
+  echo >&2 "Error: Incorrect usage. Expected: lcinit <problem number>"
   exit 1
 fi
 
 if [[ ! $1 =~ ^[0-9]{1,4}$ ]]; then
-  echo "error: usage lcinit <problem number>"
+  echo >&2 "Error: Incorrect usage. Expected: lcinit <problem number>"
   exit 1
 fi
 
@@ -18,7 +18,7 @@ if [[ ! -d "$NUM" ]]; then
 fi
 
 if [[ -f "$FILENAME" ]]; then
-  echo "error: file '$FILENAME' already exists"
+  echo >&2 "Error: File '$FILENAME' already exists"
   exit 1
 fi
 
@@ -32,7 +32,7 @@ require 'pry-nav'
 STUFF
 
 if [[ ! -f "$FILENAME" ]]; then
-  echo "error: error creating file '$FILENAME'"
+  echo >&2 "Error: failed to create file '$FILENAME'"
   exit 1
 else
   echo "$FILENAME"
